### ISSUE TITLE
Use wasm-bindgen

### ISSUE THREAD

**Issue by ghost** [ProtoDef-io/node-protodefc#5]
Include a `native/` directory that uses https://github.com/rustwasm/wasm-bindgen to wrap ProtoDefc, then have a script which only runs that build when a release is being made (or when in development)

When the release is made, only the JavaScript and the WASM blob will be released, meaning no end-user will need to have Rust installed, yet they can still enjoy the same native speeds.

**Comment by rom1504** [comment]
Ok

**Comment by ghost** [comment]
Alright, once https://github.com/ProtoDef-io/protodefc/pull/19 and https://github.com/ProtoDef-io/protodefc/pull/16 are merged, we are ready to roll.
