### ISSUE TITLE
Don't use eval (evil)

### ISSUE THREAD

**Issue by ghost** [ProtoDef-io/node-protodefc#6]
It appears that Node can facilitate loading a module from a string by using https://nodejs.org/api/modules.html

```javascript
    const Module = require('module')
    const m = new Module('', module.parent)
    m._compile('module.exports = "Hello"', '')
    console.log(m.exports)
```

**Comment by rom1504** [comment]
Ok but this is still very much equivalent of to eval. And eval is ok if you
control the input. (Which we do)

**Comment by ghost** [comment]
I believe optimizations are gained when this is used (like caching perhaps). I'll look into it.

**Comment by ghost** [comment]
Doesn't add any improvements, see Module documentation for more detail, but this is effectively equivalent to `eval`
